apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mks.mongokube.wrd
spec:
  group: mongokube.wrd
  scope: Namespaced
  versions:
    - name: beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mongoExpressImage:
                  type: string
                mongoExpressServicePort:
                  type: integer
                mongoDbImage:
                  type: string
                dbUsername:
                  type: string
                dbPassword:
                  type: string
              required: ["mongoExpressImage", "mongoDbImage","dbUsername", "dbPassword"]
            status:
              type: object
              properties:
                progress:
                  type: string
          required: ["spec"]
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Status
        type: string
        jsonPath: .status.progress
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  names:
    plural: mks
    singular: mk
    kind: Mk
    shortNames:
    - mk
