/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	beta1 "mongokube/pkg/apis/mongokube/beta1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMks implements MkInterface
type FakeMks struct {
	Fake *FakeMongokubeBeta1
	ns   string
}

var mksResource = beta1.SchemeGroupVersion.WithResource("mks")

var mksKind = beta1.SchemeGroupVersion.WithKind("Mk")

// Get takes name of the mk, and returns the corresponding mk object, and an error if there is any.
func (c *FakeMks) Get(ctx context.Context, name string, options v1.GetOptions) (result *beta1.Mk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mksResource, c.ns, name), &beta1.Mk{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beta1.Mk), err
}

// List takes label and field selectors, and returns the list of Mks that match those selectors.
func (c *FakeMks) List(ctx context.Context, opts v1.ListOptions) (result *beta1.MkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mksResource, mksKind, c.ns, opts), &beta1.MkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &beta1.MkList{ListMeta: obj.(*beta1.MkList).ListMeta}
	for _, item := range obj.(*beta1.MkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mks.
func (c *FakeMks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mksResource, c.ns, opts))

}

// Create takes the representation of a mk and creates it.  Returns the server's representation of the mk, and an error, if there is any.
func (c *FakeMks) Create(ctx context.Context, mk *beta1.Mk, opts v1.CreateOptions) (result *beta1.Mk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mksResource, c.ns, mk), &beta1.Mk{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beta1.Mk), err
}

// Update takes the representation of a mk and updates it. Returns the server's representation of the mk, and an error, if there is any.
func (c *FakeMks) Update(ctx context.Context, mk *beta1.Mk, opts v1.UpdateOptions) (result *beta1.Mk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mksResource, c.ns, mk), &beta1.Mk{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beta1.Mk), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMks) UpdateStatus(ctx context.Context, mk *beta1.Mk, opts v1.UpdateOptions) (*beta1.Mk, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mksResource, "status", c.ns, mk), &beta1.Mk{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beta1.Mk), err
}

// Delete takes name of the mk and deletes it. Returns an error if one occurs.
func (c *FakeMks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mksResource, c.ns, name, opts), &beta1.Mk{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &beta1.MkList{})
	return err
}

// Patch applies the patch and returns the patched mk.
func (c *FakeMks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *beta1.Mk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mksResource, c.ns, name, pt, data, subresources...), &beta1.Mk{})

	if obj == nil {
		return nil, err
	}
	return obj.(*beta1.Mk), err
}
